version: '3'

services:
  django:
    build:
      dockerfile: ./compose/django/Dockerfile-dev
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app/backend/
      - ./static:/app/static
      - ./media:/app/media
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db

  react:
    build:
      dockerfile: ./compose/react/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app/frontend
    stdin_open: true
    tty: true
  db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
