name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: flake8
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up environment
        run: echo SECRET_KEY="${{ secrets.SECRET_KEY }}" >> .env
      - name: Lint
        run: docker compose run --rm -e SECRET_KEY=${{ secrets.SECRET_KEY }} django flake8
  backend-test:
    needs: lint
    name: backend test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Backend Test
        run: docker compose run --rm django test
